
 const images = {
    bg_image: require('./images/background_image.png'),
    app_icon: require('./images/nectar_icon.png'),
    fruit_img: require('./images/food_images.png'),
    color_icon: require('./images/color_icon.png'),
    login_bg: require('./images/login_background.png'),
    eye_close: require('./images/eye_img.png'),
    eye_open : require('./images/eyeopen.png'),
    banner_img : require('./images/banner_img.png'),
    banana : require('./images/banana.png'),
    apple : require('./images/apple.png'),
    beef_img : require('./images/beef.png'),
    chicken : require('./images/chicken.png'),
    chillies : require('./images/chillies.png'),
    ginger : require('./images/ginger.png'),
    grocries: require('./images/grocries.png'),
    rice : require('./images/rice.png'),
    fruit_vegetable : require('./images/fruit_vegetable.png'),
    cooking_oil : require('./images/cooling_oil.png'),
    meat_fish : require('./images/meat_fish.png'),
    bakery : require('./images/bakery.png'),
    dairy : require('./images/dairy.png'),
    beverages : require('./images/bevergaes.png'),
    diet_coke : require('./images/diet_coke.png'),
    sprite_can : require('./images/spirit_can.png'),
    apple_juice : require('./images/apple_juice.png'),
    orange_juice : require('./images/orange_juice.png'),
    cocacola : require('./images/cocacola.png'),
    pepsi : require('./images/pepsi.png'),
    user_profile : require('./images/user_profile.png'),
    profile_edit_icon : require('./images/profile_edit.png'),
    orders_icon : require('./images/user_order_icon.png'),
    details_icon : require('./images/details_icon.png'),
    delivary_icon : require('./images/delivary_icon.png'),
    payment_icon : require('./images/payment_icon.png'),
    promo_icon : require('./images/promo_icon.png'),
    notification_icon : require('./images/notification_icon.png'),
    help_icon : require('./images/help_icon.png'),
    about_icon : require('./images/about_icon.png'),
    logout_icon : require('./images/logout_icon.png'),
    payment_type : require('./images/payment_type.png'),
    order_accept : require('./images/accepted.png'),
    order_decline : require('./images/order_declined.png'),

};

export default images;